set(JPET_CLOUD_CONFIG "${CMAKE_CURRENT_LIST_DIR}/../cloud/wrangler.jsonc"
  CACHE FILEPATH "Cloudflare configuration used to select the client service")
set(JPET_CLOUD_URL "" CACHE STRING "Override the cloud service URL at build time")

function(jpet_configure_cloud output_header)
  if(NOT CMAKE_SCRIPT_MODE_FILE)
    set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${JPET_CLOUD_CONFIG}")
  endif()

  if(JPET_CLOUD_URL STREQUAL "")
    file(READ "${JPET_CLOUD_CONFIG}" cloud_config)
    string(JSON routes_type ERROR_VARIABLE config_error TYPE "${cloud_config}" routes)
    if(config_error OR NOT routes_type STREQUAL "ARRAY")
      message(FATAL_ERROR "${JPET_CLOUD_CONFIG} must contain a routes array: ${config_error}")
    endif()
    string(JSON route_count LENGTH "${cloud_config}" routes)
    set(domains)
    if(route_count GREATER 0)
      math(EXPR last_route "${route_count} - 1")
      foreach(index RANGE 0 ${last_route})
        string(JSON custom_domain ERROR_VARIABLE route_error GET "${cloud_config}" routes ${index} custom_domain)
        if(route_error OR NOT custom_domain)
          continue()
        endif()
        string(JSON enabled ERROR_VARIABLE enabled_error GET "${cloud_config}" routes ${index} enabled)
        if(NOT enabled_error AND NOT enabled)
          continue()
        endif()
        string(JSON domain ERROR_VARIABLE domain_error GET "${cloud_config}" routes ${index} pattern)
        if(domain_error OR NOT domain MATCHES "^[A-Za-z0-9.-]+$")
          message(FATAL_ERROR "Cloudflare Custom Domain must contain a hostname without a scheme or path")
        endif()
        list(APPEND domains "${domain}")
      endforeach()
    endif()
    list(REMOVE_DUPLICATES domains)
    list(LENGTH domains domain_count)
    if(NOT domain_count EQUAL 1)
      message(FATAL_ERROR "Select exactly one enabled Cloudflare Custom Domain, or set -DJPET_CLOUD_URL at build time")
    endif()
    list(GET domains 0 domain)
    set(JPET_COMPILED_CLOUD_URL "https://${domain}")
  else()
    set(JPET_COMPILED_CLOUD_URL "${JPET_CLOUD_URL}")
  endif()

  string(LENGTH "${JPET_COMPILED_CLOUD_URL}" url_length)
  if(url_length GREATER 512 OR NOT JPET_COMPILED_CLOUD_URL MATCHES
      "^(https://[A-Za-z0-9.-]+(:[0-9]+)?|http://(127[.]0[.]0[.]1|localhost)(:[0-9]+)?)(/[A-Za-z0-9_./-]*)?$")
    message(FATAL_ERROR "Cloud service URL must use HTTPS; HTTP is allowed only for localhost development")
  endif()

  get_filename_component(header_directory "${output_header}" DIRECTORY)
  file(MAKE_DIRECTORY "${header_directory}")
  configure_file("${CMAKE_CURRENT_FUNCTION_LIST_DIR}/JPetCloudConfig.hpp.in" "${output_header}" @ONLY)
  message(STATUS "JPet cloud service: ${JPET_COMPILED_CLOUD_URL}")
endfunction()

if("${CMAKE_SCRIPT_MODE_FILE}" STREQUAL "${CMAKE_CURRENT_LIST_FILE}")
  if(NOT DEFINED JPET_CLOUD_HEADER)
    message(FATAL_ERROR "Set -DJPET_CLOUD_HEADER to the generated header path")
  endif()
  jpet_configure_cloud("${JPET_CLOUD_HEADER}")
endif()
